### ISSUE TITLE
Elasticsearch integration.

### ISSUE THREAD

**Issue by nisevi** [nisevi/nisevi#43]
Implement elasticsearch integration for indexing text on models 'Article'.

**Comment by merlin2049er** [comment]
I've used ransack for full text searching, elasticsearch might be overkill?

**Comment by nisevi** [comment]
Hey @merlin2049er I've never heard of ransack, I will take a look, also if you want to make a PR you are more than welcome :+1:

**Comment by nisevi** [comment]
@merlin2049er also I think first I need to fix some things in the site to leave it stable, and after that we could implement ransack :+1:
