### ISSUE TITLE
Implement timeout for session.

### ISSUE THREAD

**Issue by nisevi** [nisevi/nisevi#49]

**Comment by merlin2049er** [comment]
I've got session time out working on my rails app.  I can add this for you.  But my timeout warning doesn't work yet.  Need to investigate.

**Comment by nisevi** [comment]
@merlin2049er that would be great, if you want we could leave the information that we find here in the comments in order to keep track of what we find :+1: ... Also I don't know if you use [Zenhub](https://www.zenhub.com/), but give it a try and you will be able to see the issues in a more neat way :+1:
