### ISSUE TITLE
Create Dockerfile for development.

### ISSUE THREAD

**Issue by nisevi** [nisevi/nisevi#63]

**Comment by merlin2049er** [comment]
I believe you can do this right from Rubymine.

**Comment by nisevi** [comment]
@merlin2049er to be honest about Rubymine I tried the IDE, but I ended up with Vim as my favorite IDE. But! if you are using Rubymine and want to experiment with the creation of the Dockerfile, you can do it and your PR. it will be more than welcome.

**Comment by merlin2049er** [comment]
Ok, I'll try to get a docker file created.  

I forked your project to play around with then downloaded the source code to my desktop, but ran into some problems trying to get it running.   

I believe I had problems with aws and imagemagik.

**Comment by nisevi** [comment]
Ok during the next week I will to update the README.md file in order to be more precise on how to get it running, I have some gems that I'm not using at the moment and maybe it will be easier for anyone trying to use this project if they have either the Dockerfile for running the app in a container or the correct specifications about what is needed for the project to run.

Also so you may notice the project is not finished, and I would like to change the name #64 in order to represent more accurately what I'm or we are trying to do with this, my idea was to create a website that works as portfolio and blog, with an administration part, easy to use for the new developers that are trying the rails world :+1: in order for them to be able to launch their own sites with a descriptive wiki
